# Generated by Django 5.2.6 on 2025-09-23 22:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_category_tag_post_category_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
